app = 'jme-bot-backend'
primary_region = 'gru'

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.http_options]
    idle_timeout = 600


[mounts]
  source = "whatsapp_session"
  destination = "/data"

[[restart]]
  policy = "always"
  max_retries = 10

[[vm]]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1