# fly.toml app configuration file generated for jme-bot-backend on 2026-04-01T02:05:16-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jme-bot-backend'
primary_region = 'gru'

[build]

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 443
    handlers = ['tls']

  [[services.ports]]
    port = 80
    handlers = ['http']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
