services:
  - type: web
    name: jme-bot
    runtime: image
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 3001
      - key: VITE_API_URL
        value: https://jme-bot.onrender.com
      - key: PLANILHA_ID
        sync: false
