services:
  - type: web
    name: jme-bot-backend
    runtime: node
    repo: https://github.com/Everson9/jme-bot
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    # NÃO coloque envVars aqui!